%TRAINPATCHCNN Train the workshop patch-level crack classifier.

scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(fileparts(scriptDir));
addpath(fullfile(repoRoot, 'config'));
addpath(scriptDir);

cfg = defaultConfig();
rng(cfg.random_seed);

assert(isfolder(cfg.patch_dir), 'Patch directory not found: %s', cfg.patch_dir);
imds = imageDatastore(cfg.patch_dir, ...
    'IncludeSubfolders',true, 'LabelSource','foldernames');
disp(countEachLabel(imds));

% For a rigorous experiment, split by source image before patch extraction.
[imdsTrain, imdsValidation] = splitEachLabel(imds, 0.8, 'randomized');

augmenter = imageDataAugmenter( ...
    'RandRotation',[-15 15], ...
    'RandXReflection',true, ...
    'RandYReflection',true, ...
    'RandXTranslation',[-4 4], ...
    'RandYTranslation',[-4 4]);

trainData = augmentedImageDatastore([64 64 3], imdsTrain, ...
    'DataAugmentation',augmenter);
validationData = augmentedImageDatastore([64 64 3], imdsValidation);

layers = buildPatchCNN();
options = trainingOptions('adam', ...
    'MaxEpochs',5, ...
    'MiniBatchSize',64, ...
    'InitialLearnRate',1e-3, ...
    'Shuffle','every-epoch', ...
    'ValidationData',validationData, ...
    'ValidationFrequency',30, ...
    'Verbose',false, ...
    'Plots','training-progress', ...
    'ExecutionEnvironment','auto');

net = trainnet(trainData, layers, "crossentropy", options);
modelPath = fullfile(cfg.model_dir, 'crack_patch_cnn.mat');
save(modelPath, 'net', 'imdsValidation');
fprintf('Saved patch classifier: %s\n', modelPath);

